id: IDDAD51F0
legacy_id: P000659
ocr_import_info:
  bdrc_scan_id: W1CZ2049
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T17:49:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:13:11.815790+00:00'
last_modified: 2022-08-31 03:13:19.444518
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ2049
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ2049
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདེ་མཆོག་ཡབ་ཡུམ་ལ་བསྟོད་པ་རྐང་བརྒྱད་འགྲེལ་པ།
  author: བླ་ཁོ་འཇིགས་མེད་འཕྲིན་ལས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5639859012382634
  ocr_word_median_confidence_index: 0.5099999904632568
quality: null
bases:
  I1CZ2175:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2175
      total_pages: 34
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2175.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5639859012382634
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
