id: IDDAD51F0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:49:48+00:00'
last_modified: '2022-06-07T12:34:36.464905+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2049
  title: བདེ་མཆོག་ཡབ་ཡུམ་ལ་བསྟོད་པ་རྐང་བརྒྱད་འགྲེལ་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    87C9:
      image_group_id: I1CZ2175
      title: ''
      total_pages: 34
      order: 1
      base_file: 87C9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
