id: P000659
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:57:46.714376
source_metadata:
  id: bdr:W1CZ2049
  title: བདེ་མཆོག་ཡབ་ཡུམ་ལ་བསྟོད་པ་རྐང་བརྒྱད་འགྲེལ་པ་
  author: ''
  volumes:
    53318b07a2614c1b8e9325d82de05b7d:
      image_group_id: I1CZ2175
      title: ''
      volume_number: 1
      total_pages: 34
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
