id: P000659
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2049
  title: བདེ་མཆོག་ཡབ་ཡུམ་ལ་བསྟོད་པ་རྐང་བརྒྱད་འགྲེལ་པ་
  author: ''
  volumes:
    53318b07a2614c1b8e9325d82de05b7d:
      image_group_id: I1CZ2175
      title: ''
      volume_number: 1
      total_pages: 34
